name: Deploy Mite Reminder

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
      node-version: 14.x
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: leanovatedocker/mite-reminder
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
